### ISSUE TITLE
0x3b not escaped cause problem

### ISSUE THREAD

**Issue by bruceCzK** [matanki-saito/CK2SpecialEscape#1]
I'm using your patch for Chinese translation, and I notice some letter like '主','总', these letter's high byte is 0x3b, it is semicolon in latin1, which will lead to unexpected string split in csv file.

So I tried to add 0x3b to convertWideTextToEscapedWideText, and it worked. Hope you can make some change to fix this.

https://github.com/matanki-saito/CK2SpecialEscape/blob/286c7948727a7536dd160a902c6c735bd7ed9e71/ck2speacialescape/ck2speacialescape/ck2speacialescape.cpp#L279

**Comment by matanki-saito** [comment]
Sorry, I did not notice this issue. 🙇
I confirm.

**Comment by bruceCzK** [comment]
LOL

**Comment by matanki-saito** [comment]
https://github.com/matanki-saito/CK2SpecialEscape/commit/8d817589fff5af7bb11f3157cbc2e14b2231cc1e
done
